- name: Configure workstation type machines
  hosts: workstation
  tasks:
  - name: Enable multiarch support
    become: true
    ansible.builtin.command: dpkg --add-architecture i386
  - name: Update apt cache
    become: true
    ansible.builtin.apt:
      update_cache: true
  - name: Uninstall games
    become: true
    ansible.builtin.apt:
      name: gnome-games
      autoremove: true
      state: absent
  - name: Install Flatpak support
    become: true
    ansible.builtin.apt:
      name:
      - flatpak
      - gnome-software-plugin-flatpak
  - name: Add Flathub remote
    become: true
    community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: Remove Firefox ESR
    become: true
    ansible.builtin.apt:
      name: firefox-esr
      state: absent
  - name: Install Firefox from Flathub
    become: true
    community.general.flatpak:
      name: org.mozilla.firefox
  - name: Add Spotify key
    become: true
    ansible.builtin.apt_key:
      url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
      keyring: /etc/apt/trusted.gpg.d/spotify.gpg
  - name: Add Spotify repository
    become: true
    ansible.builtin.apt_repository:
      repo: deb http://repository.spotify.com stable non-free
      filename: spotify
  - name: Install Spotify
    become: true
    ansible.builtin.apt:
      name: spotify-client
  - name: Add Visual Studio Code key
    become: true
    ansible.builtin.apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/keyrings/packages.microsoft.gpg
  - name: Add Visual Studio Code repository
    become: true
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
      filename: vscode
  - name: Install Visual Studio Code
    become: true
    ansible.builtin.apt:
      name: code
  - name: Install git
    become: true
    ansible.builtin.apt:
      name: git
  - name: Install Steam
    become: true
    ansible.builtin.apt:
      name:
      - steam-installer
      - mesa-vulkan-drivers
      - libglx-mesa0:i386
      - mesa-vulkan-drivers:i386
      - libgl1-mesa-dri:i386
  - name: Install Gnome Boxes
    become: true
    ansible.builtin.apt:
      name:
      - gnome-boxes
      - libvirt-clients
      - libvirt-daemon-system
  - name: Add user to `libvirt` group
    become: true
    ansible.builtin.user:
      name: '{{ ansible_facts["user_id"] }}'
      groups: libvirt
      append: true
  - name: Start & Enable `libvirtd` daemon
    become: true
    ansible.builtin.service:
      name: libvirtd
      enabled: true
      state: started
  - name: Install required python3 modules
    become: true
    ansible.builtin.apt:
      name:
      - python3-libvirt
      - python3-lxml
  - name: Start and set autostart on virbr0
    become: true
    community.libvirt.virt_net:
      name: default
      command: start
      autostart: true
  - name: Configure qemu bridge
    become: true
    ansible.builtin.lineinfile:
      path: /etc/qemu/bridge.conf
      line: "allow virbr0"
      create: true
      owner: root
      group: libvirt
      mode: 0640
  - name: Set setuid bit for `qemu-bridge-helper`
    become: true
    ansible.builtin.file:
      path: /usr/lib/qemu/qemu-bridge-helper
      mode: u+s
